#!/usr/bin/env python3
# -*- coding: utf-8 -*-
###########################################################
### Imports

import numpy as np
import numpy.random as rnd
import matplotlib.pyplot as plt
import pandas as pd
from scipy import stats
import seir

###########################################################
class Person:
    
    def __init__(self, age, time):
        self.age = age #Int
        self.time = time #Float, time of arrival on certain day
        
class Patient:
    
    def __init__(self, agegroup):
        self.agegroup = agegroup
        
    def getAgeGroup(self):
        return self.agegroup
    
    def Survival(self):
        if self.agegroup == 1:
            if np.random.rand() > 0.1:
                return True
        elif self.agegroup == 2:
            if np.random.rand() > 0:
                return True
        elif self.agegroup == 3:
            if np.random.rand() > 0.154:
                return True
            else:
                return False
        elif self.agegroup == 4:
            if np.random.rand() > 0.111:
                return True
            else:
                return False
        elif self.agegroup == 5:
            if np.random.rand() > 0.1667:
                return True
            else:
                return False
        elif self.agegroup == 6:
            if np.random.rand() > 0.0612:
                return True
            else:
                return False
        elif self.agegroup == 7:
            if np.random.rand() > 0.141:
                return True
            else:
                return False
        elif self.agegroup == 8:
            if np.random.rand() > 0.112:
                return True
            else:
                return False
        elif self.agegroup == 9:
            if np.random.rand() > 0.2396:
                return True
            else:
                return False
        elif self.agegroup == 10:
            if np.random.rand() > 0.2667:
                return True
            else:
                return False
        elif self.agegroup == 11:
            if np.random.rand() > 0.3996:
                return True
            else:
                return False
        elif self.agegroup == 12:
            if np.random.rand() > 0.4654:
                return True
            else:
                return False
        elif self.agegroup == 13:
            if np.random.rand() > 0.5855:
                return True
            else:
                return False
        elif self.agegroup == 14:
            if np.random.rand() > 0.7241:
                return True
            else:
                return False
        elif self.agegroup == 15:
            if np.random.rand() > 0.6923:
                return True
            else:
                return False
        
class Event:
    def __init__(self, time = 0, typ = ''):
        self.info = (time, typ) #Bool, arr or dep
        
    def getTime (self):
        return self.info[0]

    def getType( self ):
        return self.info[1]
        
class Elist:
    
    def __init__(self, elist = []):
        self.elist = elist #Array of Events
        
    def addE(self, evt):
        if len(self.elist) == 0:
            self.elist = [evt]
        else:
            te = evt.getTime()
            if te > self.elist[-1].getTime():
                self.elist.append(evt)
            else:
                evstar = next(ev for ev in self.elist if ev.getTime() > te)
                evid = self.elist.index(evstar)
                self.elist.insert(evid, evt)   
                
    def getFirstEvent(self):
        evt = self.elist.pop(0)
        return evt

    def deleteEvent(self, i):
        evt = next(ev for ev in self.elist if ev.getIdnr()== i)
        self.elist.remove(evt)
    
def returnAge():
    vAgeGroups = np.arange(1, 16)
    pk = (0.0041, 0.0026, 0.0053, 0.0111, 0.0147, 0.0201, 0.0580, 0.0838, 0.1279, 0.1532, 0.1830, 0.1949, 0.1123, 0.02369, 0.00531)
    ageDist = stats.rv_discrete(name='ageDist', values = (vAgeGroups, pk))
    return ageDist.rvs()       
                
def procArr(dLambda, iBeds, L, dTime, iPatients):
    """Processes the arrival of a person"""
    dNewArr = ExpRANDOM(dLambda)
    eva = Event(dTime + dNewArr, 'arr')
    L.addE(eva)
        
    if iPatients < iBeds: #check if there is space on intensive care
        dStay = np.random.lognormal(2.7, 0.8) #if so, then determine how long the patient will stay
        evb = Event(dTime + dStay, 'dep') #create a new event
        L.addE(evb) #and add it to the event list
        return 1
    else:
        return 0    
        
def procDep(vAgeGroups):
    """Processes the departure of a patient"""
    pat = Patient(returnAge())
    age = pat.getAgeGroup()
    vAgeGroups = vAgeGroups.append(age)
    bSur = pat.Survival()
    if not bSur:
        return 1, age
    else:
        return 0, age

def ExpRANDOM(dRate):
    return -np.log(rnd.rand())/dRate     
            
def simRun(vLambda, iBeds, vPatients, vDeaths, vRej, vRD):
    dTime = 0 #starting time
    iPatients = 0 #starting amount of patients
    iDeaths = 0
    iDay = 0 #starting day
    iRej = 0
    iRD = 0
    vAgeGroups = []
    vAgeD = []
    L = Elist()
    evt = Event(ExpRANDOM(vLambda[0]), 'arr') # first arrival is someone with corona
    L.addE(evt)
    
    """Here the simulation is run for 100 days, so dTime gets added up until it is equal to 99"""
    while dTime < 99:
        dLambda = vLambda[iDay] #search for the lambda of the day
        evt = L.getFirstEvent() #search for the first event in the list
        dType = evt.getType() #find the type of event, either arrival or departure
        dTime = evt.getTime() #get the time of the event
        iDay = int(dTime) #check what day it is
        vPatients[iDay] = iPatients #set the current amount of patients on IC equal to the patients on the right day
        vDeaths[iDay] = iDeaths
        vRej[iDay] = iRej
        vRD[iDay] = iRD
        
        """Two possibilities: it is an arrival or a departure"""
        if dType == 'arr': 
            N = procArr(dLambda, iBeds, L, dTime, iPatients)
            iPatients += N
            iRej += 1 - N
            if N == 0:
                r = (np.random.choice(2, p = [0.02, 0.98]))
                iDeaths += r
                iRD += r
        else:
            r, age = procDep(vAgeGroups)
            iDeaths += r
            if r == 1:
                vAgeD.append(age)
            iPatients -= 1 
           
        
    vPatients[-1] = vPatients[-2]
    vDeaths[-1] = vDeaths[-2]
    vRej[-1] = vRej[-2]
    vRD[-1] = vRD[-2]
    
    return vPatients, vDeaths, vAgeGroups, vRej, vRD, vAgeD

def Simulations(iN, iDays, dP, dLambda, dGammaMild, dGammaHard, iBeds, iSimRuns):
    
    vPatientsCum = np.zeros(101)
    vDeathsCum = np.zeros(101)
    vRej = np.zeros(101)
    vRD = np.zeros(101)
    vAgeGroupsCum = [] 
    vAgeDCum = []
    for i in range(iSimRuns):
        vLambda = seir.SEIRmodel(iN, iDays, dP, dLambda, dGammaMild, dGammaHard)
        (vPatients, vDeaths, vAgeGroups, vRej, vRD, vAgeD) = simRun(vLambda, iBeds, np.zeros(101), np.zeros(101), vRej, vRD)
        
        vPatientsCum += vPatients
        #print(vPatientsCum)
        #print(vPatients)
        vDeathsCum += vDeaths
        vAgeGroupsCum.extend(vAgeGroups)
        vAgeDCum.extend(vAgeD)
        
    vPatients = vPatientsCum / iSimRuns
    vDeaths = vDeathsCum / iSimRuns
    vRej = vRej / iSimRuns
    vRD = vRD / iSimRuns
    return (vPatients, vDeaths, vRej, vAgeGroups, vRD, vAgeD)    
    
def barToLine(vA):
    vB = np.zeros(max(vA))
    for i in vA:
        vB[i - 1] += 1
    return vB

def calcMortality(vNum, vDen):
    vA = np.zeros(len(vNum))
    for i in range(len(vNum)):
        vA[i] = vNum[i]/vDen[i]
    return vA

def occupy(iBeds, vPatients):
    vA = np.zeros(len(vPatients))
    for i in range(len(vPatients)):
        vA[i] = vPatients[i] / iBeds
    return vA

def printMortality(vA, vB):
    for i in range(len(vA)):
        print(str(round(100*vA[i], 3)) + "% of age group", i + 1, "died, based on", int(vB[i]), "patients.")
    
def main(): 
    url2 = 'https://raw.githubusercontent.com/J535D165/CoronaWatchNL/master/data-ic/data-nice/NICE_IC_wide_latest.csv'
    df2 = pd.read_csv(url2, error_bad_lines=False)
    dfICdata = df2.loc[:, "TotaalOpnamen"]
    vICdata = dfICdata.values
    
    iSimRuns = 1
    iBeds = 1210
    vPatients = np.zeros(101)
    
    iN = 17414806 #population
    iN = 0.06 * iN #population infected in Netherlands estimated
    iDays = 110 
    dP = 0.003 #percentage of IC from total people infected
    
    dLambda = 0.167 #incubatietijd van coronavirus 1/days
    dGammaMild = 0.125 #duur van herstel voor milde gevallen 1/days
    dGammaHard = 0.0556 #duur van herstel voor zware gevallen 1/days
    
    (vPatients, vDeaths, vRej, vAgeGroups, vRD, vAgeD) = Simulations(iN, iDays, dP, dLambda, dGammaMild, dGammaHard, iBeds, iSimRuns)
    plt.plot(vPatients, label='Simulated patients') #our simulation
    plt.plot(vICdata, label='Given data') #real data
    plt.plot(vDeaths, label='Deaths')
    plt.plot(vRej, label='Rejected patients')
    plt.hlines(iBeds, 0, 100, label='Beds')
    plt.title('Number of patients over time')
    ax = plt.subplot(111)
    ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    plt.show()
    
    print(str(int(vRej[100])) + " people were rejected, of which " + str(int(vRD[100])) + " people died.")
    print(str(len(vAgeGroups)) + " people left the IC, of which " + str(len(vAgeD)) + " dead.") 
    print("Which comes down to a total deathcount of " + str(int(vDeaths[100])) + ".")
    
    plt.hist(vAgeGroups, bins=15, label='Patients')
    plt.hist(vAgeD, bins=15, label='Deaths')
    plt.title('Patients & Deaths per age group')
    ax = plt.subplot(111)
    ax.legend(loc='center left', bbox_to_anchor=(1, 0.5))
    plt.show()
    
    vOcc = occupy(iBeds, vPatients)
    plt.plot(vOcc)
    plt.title('Percentage of beds being occupied')
    plt.show()
    
    vBarsDep = barToLine(vAgeGroups)
    vBarsDea = barToLine(vAgeD)
    vMort = calcMortality(vBarsDea, vBarsDep)
    printMortality(vMort, vBarsDep)
    
###########################################################
### start main
if __name__ == "__main__":
    main()
